server:
  port: 9001
  servlet:
    session:
      cookie:
        name: id_${spring.application.name}_${spring.profiles.active}
debug: false
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  application:
    name: oauth2sso
  profiles:
    active: dev