server:
  port: 9001
  servlet:
    session:
      cookie:
        name: ${spring.application.name}_${spring.profiles.active}
debug: true
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  application:
    name: oauth2sso
  profiles:
    active: dev
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:9001/user
      service-id: oauth2-sso
#io24m:
#  indexPage: https://github.com/io24m/oauth2-sso