server:
  port: 9004
  servlet:
    session:
      cookie:
        name: ${spring.application.name}_${spring.profiles.active}
spring:
  application:
    name: client
  profiles:
    active: dev
security:
  oauth2:
    client:
      client-id: test-client-id
      client-secret: test-client-secret
      access-token-uri: http://localhost:9001/oauth/token
      user-authorization-uri: http://localhost:9001/oauth/authorize
    resource:
      #      service-id: admin-service
      user-info-uri: http://localhost:9001/user
